server:
  port: 8090
spring:
  cloud:
    gateway:
      default-filters:
        - AddResponseHeader=source, yxs
      routes:
          # 定义了一个名为"api_route"的路由规则,该规则将匹配以"/api/"开头的路径,例如"/api/user",
          # 并将这些请求转发到"http://localhost:8123"这个目标地址
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/api/**
#        - id: after_route
#          uri: https://yupi.icu
#          predicates:
#            - After=2017-01-20T17:42:47.789-07:00[America/Denver]
        # ??????/api/**??????????URI https://yupi.icu
#        - id: path_route
#          uri: https://yupi.icu
#          predicates:
#            - Path=/api/**
#        # ??????/baidu/**??????????URI https://baidu.com
#        - id: path_route2
#          uri: https://baidu.com
#          predicates:
#            - Path=/baidu/**
#          - id: add_request_header_route
#            uri: http://localhost:8123
#            predicates:
#              - Path=/api/**
#            filters:
#              - AddRequestHeader=yxs, swag
#              - AddRequestParameter=name, dog
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace

